# Generated by Django 5.0.3 on 2024-03-27 18:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_remove_question_answers_answerfile_exam_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='score',
        ),
        migrations.AddField(
            model_name='exam',
            name='total_marks',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.CreateModel(
            name='StudentExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('enrolled', 'Enrolled'), ('completed', 'Completed'), ('incomplete', 'Incomplete'), ('withdrawn', 'Withdrawn')], default='enrolled', max_length=20, verbose_name='status')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='score')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='start time')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='end time')),
                ('attempts', models.PositiveIntegerField(default=0, verbose_name='attempts')),
                ('feedback', models.TextField(blank=True, verbose_name='feedback')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('duration', models.DurationField(blank=True, null=True, verbose_name='duration')),
                ('submission_status', models.BooleanField(default=False, verbose_name='submission status')),
                ('flagged_for_review', models.BooleanField(default=False, verbose_name='flagged for review')),
                ('access_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='access code')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.exam', verbose_name='exam')),
                ('proctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proctoring_exams', to=settings.AUTH_USER_MODEL, verbose_name='proctor')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='student')),
            ],
        ),
    ]
