# Generated by Django 5.0.3 on 2024-03-27 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_remove_exam_score_exam_total_marks_studentexam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentexam',
            name='submission_status',
            field=models.BooleanField(default=False, null=True, verbose_name='submission status'),
        ),
    ]
