# Generated by Django 5.0.3 on 2024-03-28 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_alter_studentexam_submission_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='exam_documnets/'),
        ),
    ]
