# Generated by Django 5.0.3 on 2024-03-28 05:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_exam_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 3, 28, 5, 17, 53, 790509, tzinfo=datetime.timezone.utc), verbose_name='exam date'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='exam_documents/'),
        ),
    ]
